
Widget:

<CustomDropDown>:
    Button:
        text: 'My first Item'
        size_hint_y: None
        height: 44
        # 릴리즈시 select 이벤트를 호출
        on_release: root.select('item1')
    Label:
        text: 'Unselectable item'
        size_hint_y: None
        height: 44
        # Label에는 on_release가 없다
    Button:
        text: 'My second Item'
        size_hint_y: None
        height: 44
        # 릴리즈시 select 이벤트를 호출
        on_release: root.select('item2')
